extends: default

# Ignore Helm templates (contain Go template syntax)
ignore:
  - "charts/*/templates/"

rules:
  line-length:
    max: 120
  indentation:
    spaces: 2
  document-start: disable
  truthy:
    check-keys: false
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
