---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: media-critical
  annotations:
    argocd.argoproj.io/sync-wave: "0"
globalDefault: false
value: 1000000
description: "Critical media services (DNS)"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: media-high
  annotations:
    argocd.argoproj.io/sync-wave: "0"
globalDefault: false
value: 900000
description: "High priority media services (Plex, qBittorrent)"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: media-normal
  annotations:
    argocd.argoproj.io/sync-wave: "0"
globalDefault: false
value: 800000
description: "Normal priority media services"
