apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    # ArgoCD Image Updater
    argocd-image-updater.argoproj.io/image-list: qbittorrent=lscr.io/linuxserver/qbittorrent
    argocd-image-updater.argoproj.io/qbittorrent.update-strategy: semver
    argocd-image-updater.argoproj.io/qbittorrent.semver-constraint: "*"
    argocd-image-updater.argoproj.io/qbittorrent.allow-tags: regexp:^[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/qbittorrent.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/qbittorrent.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:values.yaml
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/muchiny/media-stack-k8s.git
    targetRevision: HEAD
    path: charts/qbittorrent
    helm:
      releaseName: media
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: media-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
