---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: media-stack-quota
  namespace: media-stack
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "6Gi"
    limits.cpu: "6"
    limits.memory: "8Gi"
